[package]
name = "codegen-bindings-generator"
version = "0.1.0"
edition = "2024"

[dependencies]
quote = { workspace = true }
codegen-sdk-common = { workspace = true }
syn = { workspace = true }
anyhow = { workspace = true }
