[package]
name = "codegen-sdk-core"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.28", features = ["derive"] }
codegen-sdk-analyzer = { path = "codegen-sdk-analyzer" }
codegen-sdk-cst = { path = "codegen-sdk-cst" }
crossbeam = "0.8.4"
env_logger = "0.11.6"
glob = "0.3.2"
log = { workspace = true }
rayon = "1.10.0"
sysinfo = "0.33.1"
[workspace]
members = [
  "codegen-sdk-analyzer",
  "codegen-sdk-ast",
  "codegen-sdk-common",
  "codegen-sdk-cst",
  "codegen-sdk-cst-generator",
]
[workspace.dependencies]
log = "0.4.25"
ouroboros = "0.18.5"
tree-sitter = "0.25.1"
tree-sitter-python = "0.23.6"
tree-sitter-typescript = "0.23.2"
bytes = "1.10.0"
convert_case = "0.7.1"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
