name: "Setup Environment"
description: "Setup Environment"
runs:
  using: "composite"
  steps:
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - uses: taiki-e/install-action@nextest
    - name: Install Cranelift
      run: |
        rustup component add rustc-codegen-cranelift-preview --toolchain nightly
      shell: bash
