name: "Setup Environment"
description: "Setup Environment"
runs:
  using: "composite"
  steps:
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: nightly
        components: rustc-codegen-cranelift-preview, rustfmt
        cache-on-failure: true
    - uses: taiki-e/install-action@nextest
