[package]
name = "codegen-sdk-cst"
version = "0.1.0"
edition = "2021"

[dependencies]
tree-sitter = { workspace = true }
tree-sitter-python = { workspace = true }
ouroboros = { workspace = true }
tree-sitter-typescript = { workspace = true }
bytes = { workspace = true }
codegen-sdk-common = { path = "../codegen-sdk-common" }
convert_case = { workspace = true }
[build-dependencies]
codegen-sdk-cst-generator = { path = "../codegen-sdk-cst-generator" }
codegen-sdk-common = { path = "../codegen-sdk-common" }
tree-sitter-python = { workspace = true }
tree-sitter-typescript = { workspace = true }

[dev-dependencies]
tempfile = "3.16.0"
