[package]
name = "codegen-sdk-cst"
version = "0.1.0"
edition = "2024"

[dependencies]
tree-sitter = { workspace = true }
bytes = { workspace = true }
codegen-sdk-common = { path = "../codegen-sdk-common", features = ["ts_query"] }
codegen-sdk-macros = { path = "../codegen-sdk-macros" }
derive_more = { version = "2.0.1", features = ["debug", "display"] }
convert_case = { workspace = true }
rkyv = { workspace = true }
subenum = "1.1.2"
log = { workspace = true }
enum_delegate = { workspace = true }
derive-visitor = "0.4.0"
[build-dependencies]
codegen-sdk-cst-generator = { path = "../codegen-sdk-cst-generator"}
codegen-sdk-common = { path = "../codegen-sdk-common", features = ["all"] }
rayon = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
[dev-dependencies]
tempfile = "3.16.0"
test-log = { workspace = true }
[features]
python = [ "codegen-sdk-common/python"]
typescript = [ "codegen-sdk-common/typescript"]
tsx = [ "codegen-sdk-common/typescript"]
jsx = [ "codegen-sdk-common/typescript"]
javascript = [ "codegen-sdk-common/typescript"]
json = [ "codegen-sdk-common/json"]
java = [ "codegen-sdk-common/java"]
ts_query = []
default = ["json", "ts_query"]
