[package]
name = "codegen-sdk-macros"
version = "0.1.0"
edition = "2021"

[dependencies]
codegen-sdk-common = { path = "../codegen-sdk-common", features = ["typescript", "python"] }
[lib]
proc-macro = true
