[package]
name = "codegen-sdk-macros"
version = "0.1.0"
edition = "2024"

[dependencies]
codegen-sdk-common = { workspace = true}
quote = { workspace = true }
proc-macro2 = { workspace = true }
[lib]
proc-macro = true
