[package]
name = "codegen-sdk-cst-generator"
version = "0.1.0"
edition = "2021"

[dependencies]
convert_case = { workspace = true }
phf = { version = "0.11.3", features = ["macros"] }
prettyplease = "0.2.29"
syn = "2.0.98"
tree-sitter = { workspace = true }
log = { workspace = true }
codegen-sdk-common = { path = "../codegen-sdk-common" }
anyhow = { workspace = true }
[dev-dependencies]
codegen-sdk-common = { path = "../codegen-sdk-common" , features = ["python"] }
