[package]
name = "codegen-sdk-analyzer"
version = "0.1.0"
edition = "2024"

[dependencies]
salsa = { workspace = true }
codegen-sdk-ast = { workspace = true }
[dev-dependencies]
test-log = { workspace = true }
