[package]
name = "codegen-sdk-ast"
version = "0.1.0"
edition = "2024"

[dependencies]
codegen-sdk-cst = { workspace = true, features = ["json"]}
codegen-sdk-common = { workspace = true }

[build-dependencies]
codegen-sdk-common = { workspace = true }
env_logger = { workspace = true }
rayon = { workspace = true }
codegen-sdk-ast-generator = { path = "../codegen-sdk-ast-generator"}
[features]
python = [ "codegen-sdk-cst/python"]
typescript = [ "codegen-sdk-cst/typescript"]
tsx = [ "codegen-sdk-cst/tsx"]
jsx = [ "codegen-sdk-cst/jsx"]
javascript = [ "codegen-sdk-cst/typescript"]
json = [ "codegen-sdk-cst/json"]
java = [ "codegen-sdk-cst/java"]
ts_query = []
default = ["json", "ts_query"]
